### PR TITLE
fix: Upgrade to cobalt#346

### PR DESCRIPTION
**Pull request by epage**
Feedback on https://github.com/cobalt-org/cobalt.rs/pull/346 is welcome.  In addition to this PR, you can peruse the updated [documentation](https://cobalt-org.github.io/).

Commands run
- `cobalt migrate`
- `rm _includes/default.liquid`
- `rm _includes/post.liquid`
- `rm _includes/site.liquid`
- `rm _layouts/_*.liquid`
- Edited `_includes/head.liquid` to remove bad `{{#title}}`, etc

### CODE REVIEW

**Comment by epage** [comment]
v0.11 is now released

**Comment by badboy** [comment]
Why did you remove the `_includes`? They are necessary. Adding them back.

**Comment by epage** [comment]
The original `_layouts` directory is now split into `_layouts` and `_includes`.

Migration was implemented naively.  It copies all of `_layouts` to `_includes`.  This means the `_layouts` directory has dead files in it and the `_includes` directory has dead files in it.

I tried to figure out which were dead files and delete them (and recorded them in the PR for reference).  I thought my build came back clean so I thought I had gotten it right.  I'm sorry if I goofed this up.

**Comment by badboy** [comment]
Was easy to fix. Thanks anyway!

**Pull request merged**
